library(tidyverse)
library(tidytext)

#first run import transcripts to get the data

AFINN <- get_sentiments("afinn")

sent <- function(comedian_norm){
  df <- inner_join(comedian_norm, AFINN) %>% mutate(weight = score*rf)
  sum = sum(df$weight)
  return(sum)
}

AW_sent <- inner_join(AW_norm, AFINN) %>% mutate(weight = score*rf)
sum(AW_sent$weight)
sent(JC_norm)
sent(JG_norm)

comedy_sentiments <- cbind(comedians_list, c(0))
colnames(comedy_sentiments) <- c("Comedian", "Average Sentiment Score")
comedy_sentiments <- as.tibble(comedy_sentiments)

comedy_sentiments$`Average Sentiment Score`[1] <- sent(AS_norm)
comedy_sentiments$`Average Sentiment Score`[2] <- sent(AA_norm)
comedy_sentiments$`Average Sentiment Score`[3] <- sent(AW_norm)
comedy_sentiments$`Average Sentiment Score`[4] <- sent(Burr_norm)
comedy_sentiments$`Average Sentiment Score`[5] <- sent(BH_norm)
comedy_sentiments$`Average Sentiment Score`[6] <- sent(BB_norm)
comedy_sentiments$`Average Sentiment Score`[7] <- sent(BP_norm)
comedy_sentiments$`Average Sentiment Score`[8] <- sent(CR_norm)
comedy_sentiments$`Average Sentiment Score`[9] <- sent(DC_norm)
comedy_sentiments$`Average Sentiment Score`[10] <- sent(DM_norm)
comedy_sentiments$`Average Sentiment Score`[11] <- sent(DG_norm)
comedy_sentiments$`Average Sentiment Score`[12] <- sent(DT_norm)
comedy_sentiments$`Average Sentiment Score`[13] <- sent(EM_norm)
comedy_sentiments$`Average Sentiment Score`[14] <- sent(FB_norm)
comedy_sentiments$`Average Sentiment Score`[15] <- sent(GC_norm)
comedy_sentiments$`Average Sentiment Score`[16] <- sent(IS_norm)
comedy_sentiments$`Average Sentiment Score`[17] <- sent(JF_norm)
comedy_sentiments$`Average Sentiment Score`[18] <- sent(JC_norm)
comedy_sentiments$`Average Sentiment Score`[19] <- sent(JG_norm)
comedy_sentiments$`Average Sentiment Score`[20] <- sent(JJ_norm)
comedy_sentiments$`Average Sentiment Score`[21] <- sent(JM_norm)
comedy_sentiments$`Average Sentiment Score`[22] <- sent(CK_norm)
comedy_sentiments$`Average Sentiment Score`[23] <- sent(LB_norm)
comedy_sentiments$`Average Sentiment Score`[24] <- sent(MB_norm)
comedy_sentiments$`Average Sentiment Score`[25] <- sent(NB_norm)
comedy_sentiments$`Average Sentiment Score`[26] <- sent(PO_norm)
comedy_sentiments$`Average Sentiment Score`[27] <- sent(RP_norm)
comedy_sentiments$`Average Sentiment Score`[28] <- sent(RW_norm)
comedy_sentiments$`Average Sentiment Score`[29] <- sent(RG_norm)
comedy_sentiments$`Average Sentiment Score`[30] <- sent(SH_norm)
comedy_sentiments$`Average Sentiment Score`[31] <- sent(TS_norm)
comedy_sentiments$`Average Sentiment Score`[32] <- sent(SW_norm)
comedy_sentiments$`Average Sentiment Score`[33] <- sent(RF_norm)
comedy_sentiments$`Average Sentiment Score`[34] <- sent(JS_norm)
comedy_sentiments$`Average Sentiment Score`[35] <- sent(HB_norm)
comedy_sentiments$`Average Sentiment Score`[36] <- sent(LC_norm)
comedy_sentiments$`Average Sentiment Score`[37] <- sent(MH_norm)
comedy_sentiments$`Average Sentiment Score`[38] <- sent(BE_norm)
